echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo "this is my 2nd push"
ECHO "THIS IS REVISION"
echo "this edit in Amol_branch"
echo "this is merge conflict"